---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: k-instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
  host_vars:
    k-instance:
      ansible_user: kibana
verifier:
  name: ansible
